title: "Cards"
description: |
  Cards should be used when there are multiple image and type groups.

patterns:
    card-project:
      title: "Project Card"
      description: |
        The Project Cards are used on the homepage to lead viewers to each individual project page. Each of them must have the project name and their field.
      fields:
        - name: heading
          type: string
          example: "LaundroMate"
        - name: text
          type: string
          example: "App Design 	&#9679; UI/UX"
        - name: image
          type: string
          example: "/images/laundromate.jpg"
        - name: button_url
          type: url
          example: "/laundromate/"
          required: false
    card-intro:
      title: "Section Intro Card"
      description: |
        The Section Cards are used as the top left side item on each section on large screens and the top item on small screens.
      fields:
        - name: heading
          type: string
          example: "HELLO"
        - name: text
          type: string
          example: "Sophie Riopel is a UI/UX Designer."
        - name: text-2
          type: string
          example: "I spend most of my days scouring the web with online shopping and find severe joy with all the different UI layouts I come across. The idea of finding cool products online with ease blows my mind. When an eCommerce website is too hard to navigate through, I immediately start thinking of why it's not working and how to fix it. The idea that there are awesome products online but people struggle with getting to them, breaks my soul."
        - name: text-3
          type: string
          example: "I spend way too much time thinking about other people and finding solutions for them. That's when I realized that I wanted to design cool websites and apps to help users get excited about their upcoming packages."
    card-about:
      title: "About Me Card"
      description: |
        The About Me Card is only used on the homepage following the section card. This card will include my name, logo and social media links.
      fields:
        - name: heading
          type: string
          example: "Sophie Riopel"
        - name: image
          type: string
          example: "/images/logo-sr.svg"
    card-contact:
      title: "Contact Card"
      description: |
        The Contact Card is used on the contact page. It will contain the contact forms.
      fields:
        - name: email-label
          type: string
          example: "Email"
        - name: text
          type: string
          example: "Submit"
        - name: area-label
          type: string
          example: "Message"
        - name: text-label
          type: string
          example: "Text Input"
    card-image-right:
      title: "Image Right Card"
      description: |
        The Image Right Card is used on the project pages. It will contain information about the steps taken in creation of the project. The cards Image Right Card and Image Left Card must be alternated.
      fields:
        - name: heading
          type: string
          example: "Step 1"
        - name: text
          type: string
          example: "This is the part where the explaination goes in."
        - name: image
          type: string
          example: "/images/laundromate.jpg"
        - name: alt
          type: string
          example: "the description of the image goes here"
    card-image-left:
      title: "Image Left Card"
      description: |
        The Image Left Card is used on the project pages. It will contain information about the steps taken in creation of the project. The cards Image Left Card and Image Right Card must be alternated.
      fields:
        - name: heading
          type: string
          example: "Step 2"
        - name: text
          type: string
          example: "This is the part where the explaination goes in."
        - name: image
          type: string
          example: "/images/jolie.jpg"
        - name: alt
          type: string
          example: "the description of the image goes here"
    card-project-header:
      title: "Project Header Card"
      description: |
        The Project Header Card is used as the first thing on the project pages.
      fields:
        - name: heading
          type: string
          example: "LaundroMate"
        - name: subheading
          type: string
          example: "App Design 	&#9679; UI/UX"
        - name: image
          type: string
          example: "/images/laundromate-header.jpg"
        - name: text
          type: string
          example: "This is where the description and explaination of the project goes."
        - name: alt
          type: string
          example: "the description of the image goes here"
    card-image-full:
      title: "Full Height Half Width Image Card"
      description: |
        The Full Height Half Width Image Card is used as to place an image.
      fields:
        - name: image
          type: string
          example: "/images/laundromate-header.jpg"
        - name: alt
          type: string
          example: "the description of the image goes here"
    card-project-head-left:
      title: "Project Header Left"
      description: |
        The Project Header Left Card is used to place an image of the project in the header.
      fields:
        - name: image
          type: string
          example: "/images/placeholder.jpg"
        - name: alt
          type: string
          example: "the description of the image goes here"
    card-project-head-right:
      title: "Project Header Right"
      description: |
        The Project Header Right Card is used to show project info.
      fields:
        - name: title
          type: string
          example: "Project Title"
        - name: client
          type: string
          example: "Client Name"
        - name: type
          type: string
          example: "Field Type"
        - name: size
          type: string
          example: "1"
        - name: date
          type: string
          example: "June 2018 - July 2018"
    card-project-about:
      title: "Project About"
      description: |
        The Project Header Left Card is used to place an image of the project in the header.
      fields:
        - name: image
          type: string
          example: "/images/placeholder.jpg"
        - name: alt
          type: string
          example: "the description of the image goes here"
        - name: intro
          type: string
          example: "Project Intro"
        - name: info
          type: string
          example: "Project info"
        - name: link
          type: url
          example: "#"
        - name: link-name
          type: string
          example: "Button Basic"
